[package]
name = "opal-wm"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["libgem", "libgems", "libserver", "libserver/msg-macros", "libopal", "opal-abi", "opal-img", "uopal-desktop", "luneaudio", "lune-abi", "libartemis"]

[dependencies]
safa-api = { version = "0.6.0", git = "https://github.com/SafaOS/safa-api", features = ["std"] }
libopal = { path = "libopal" }
opal-abi = { path = "opal-abi" }
opal-img = { path = "opal-img" }
thiserror = "2.0.14"
zerocopy = "0.8.26"
zerocopy-derive = "0.8.26"
rustc-hash = "2.1.1"
indexmap = "2.10.0"
slab = "0.4.11"
arrayvec = "0.7.6"
libserver = { path = "libserver" }
libblur = { version = "0.23.3", default-features = false, features = ["sse", "neon"] }

[profile.release]
debug = 2
lto = true
overflow-checks = true
