[package]
name = "libgems"
version = "0.1.0"
edition = "2024"

[dependencies]
cosmic-text = { version = "0.16", default-features = false, features = ["std", "swash"] }
libopal = { path = "../libopal" }
tiny-skia = { version = "0.12.0", default-features = false, features = ["std", "simd"] }
uopal-desktop = { path = "../uopal-desktop" }
