[package]
name = "libserver"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
bitflags = "2.9.2"
wide = "0.7.33"
msg-macros = { path = "msg-macros" }
bytemuck = "1.24.0"
thiserror = "2.0.18"
safa-api = { version = "0.4.3", git = "https://github.com/SafaOS/safa-api", features = ["std"] }
futures-util = "0.3.31"
